# coding=utf-8
import sqlite3

with sqlite3.connect("familjen.db") as connection:
	c = connection.cursor()
	c.execute("DROP TABLE members")
	c.execute("CREATE TABLE members(imageref TEXT, name TEXT, about TEXT, joined TEXT)")
	c.execute('INSERT INTO members VALUES("bob.jpg", "Bob", "Bob är spexens mästare. Med sin enorma inlevelse kan han få vem som helst att bli en stjärna när det gäller spex. Han är en av de som sett till att punschen nu flödar på BTH. ", "2006")')
	c.execute('INSERT INTO members VALUES("brother.jpg", "brother", "Oavsett om det gäller festande eller studentpolitik så kan du ge dig på att brother är på plats. Liksom Bob skyldig till att punschen flödar på BTH.", "2006")')
	c.execute('INSERT INTO members VALUES("matte.jpg", "matte", "Mannen med kollen. Föregångaren till Yeti när det gäller snällhet och Pölsa när det gäller organisation.", "2006")')
	c.execute('INSERT INTO members VALUES("dalurka.jpg", "dalurka", "Denna man från landet skåne, aka.lurkan/lurka bjuder dig gärna på Pálinka med ett leende på läpparna. Även i de lugnaste vatten... ", "2006")')
	c.execute('INSERT INTO members VALUES("linc.jpg", "linc", "Åldermannen från TBV. Han var med när man byggde pyramiderna, korsfäste Jesus och när Bell uppfann telefonen. Omatchad när det gäller kunskap. Lika mysig som snäll. ", "2006")')
	c.execute('INSERT INTO members VALUES("lunde.jpg", "lunde", "Denne hårfagre man från norr ser till att Sverige får internet. Han är den modell efter vilken Pölsa skapades och är en av få som inte går att finna på ansiktsboken. ", "2006")')
	c.execute('INSERT INTO members VALUES("plundra.jpg", "plundra", "Plundra är mannen som postar länkar på allt från vackra kvinnor till fantastiskt söta kattungar på IRC. Han bjuder gärna på Stroh 80 eller något annat starkt och gott och är argare på internet än i verkligheten.", "2006")')
	c.execute('INSERT INTO members VALUES("spaam.jpg", "spaam", "Denna punschälskande människa kommer från norrland. Det är vida kännt att man inte klickar på de länkar som denna herre spammar i allehanda kanaler på IRCen. ", "2006")')
	c.execute('INSERT INTO members VALUES("nini.jpg", "nini", "Den första kvinnan i Familjen. Även kallad för mamma trots sin ringa ålder. Alla Familjer behöver ju en mamma som håller koll på dem!", "2007")')
	c.execute('INSERT INTO members VALUES("elm.jpg", "elm", "Lilla Edet represents! Västkustare som dricker öl snabbare än du dricker vatten. Har med Bob som mentor blivit en mästare på att komma på spex åt dig... gör du det inte så dyker glasblåsarsonen fram.... något du inte vill.", "2008")')
	c.execute('INSERT INTO members VALUES("ymer.jpg", "Ymer", "Tvekar inte att dricka sig vare whisky, aurora, punsch eller öl. Före detta hustomte på TBV som styrde sitt hus med järnhand. Om du hör sång så är Ymer säkert på plats och bidrar med sin stämma.", "2008")')
	c.execute('INSERT INTO members VALUES("bravo.jpg", "Bravo", "Den yngste i Familjen. Finsmakare av både whisky och öl som hatar kåren innan han fått lite i sig. Familjens meste fotograf.", "2009")')
	c.execute('INSERT INTO members VALUES("strand.jpg", "strand", "Markus Strand. Den evige. Tidsbaronen som trotsade sanden i timglaset! Mannen, myten, legenden har återvänt till Karlskrona för att röja loss och skapa nya fiender! ", "2010")')
	c.execute('INSERT INTO members VALUES("string.jpg", "string", "Denna skönsångande göteborgare var den första i Familjen som som lyckats med bedriften att komma med i Familjen utan att ha läst en enda kurs på BTH.", "2010")')
	c.execute('INSERT INTO members VALUES("amer.jpg", "Amer", "Hans ursprung varierar beroende på vem du frågar. En sak är säker, när han blir full så åker kläderna av och han börjar dansa med en flaska Aurora i näven. Har en viss fallenhet för WoW och andra onlinespel. ", "2011")')
	c.execute('INSERT INTO members VALUES("marty.jpg", "Marty", "Mannen som blev så arg att han spydde över bardisken när han inte fick köpa trisslotter på kåren. Går inte att stressa hur mycket man än försöker. Ses ofta med en flaska rom i handen. Den siste i Familjen att överge TBV.", "2011")')
	c.execute('INSERT INTO members VALUES("poelsa.jpg", "Pölsa", "Nej det är inte den danska korven! Pölsa eller som han också är känd Lunde.v2 är en rockande (lol) 08. Upphovsman till uttryck så som vafan() och åh neej. ", "2011")')
	c.execute('INSERT INTO members VALUES("sara.jpg", "Little Waif", "Sara är tjejen som är arg med ett leende på läpparna. Var mästerkocken på Krebo om man räknar att öppna Pringlesburkar till matlagning. Ryktet går att hon ibland åker till Polen för att köpa horor.", "2012")')
	c.execute('INSERT INTO members VALUES("endl.jpg", "endl;", "endl; är en lurig filur. Sveriges meste bänknötare i handboll. När det gäller fest så vill endl; se spex och då helst På ett järnvägsspår. Genomförs det inte korrekt så kommer ursinnet fram och man får vara glad om alla kommer levande därifrån.", "2012")')
	c.execute('INSERT INTO members VALUES("lautta.jpg", "Lautta", "Även känd som spritLautta. Så gullig och söt när du träffar henne, sen börjar hon retas... Med finskt blood i kroppen så är hon glad för att sticka folk med knivar.", "2013")')
	c.execute('INSERT INTO members VALUES("ela.jpg", "ela", "Ela är kvinnan som ska undervisa Sverige. Hon förser oss alla med pannkakor och sjunger gärna för dig när du minst anar det. Den första i Familjen som pluggat i Kristianstad ", "2013")')
	c.execute('INSERT INTO members VALUES("yeti.jpg", "Yeti", "Yeti är en stor sak som är snällare än en sten och har ett hjärta av punsch. Utbildar sig till WIP:are. Längst i Familjen vilket är bra... han är lätt att hitta på varenda studentphest!", "2013")')
	c.execute('INSERT INTO members VALUES("wire.jpg", "Wireshark", "Denna tysta filosof från Könjöping vet vad folk gillar, whisky! Är duktig på att supa ner sig själv och en av få som inte kan sjunga för fem öre. Tondöv och taktlös men vad gör det när man är så förbannat trevlig?", "2013")')
	c.execute('INSERT INTO members VALUES("mira.jpg", "Mira", "Trots sin ringa storlek hörs och syns hon mest. Mira är en klad figur och ägare till KAAAATHEEEEN! Fruktansvärt liten och energisk. Första tillskottet till Familjen från Halmstad. ", "2013")')
	c.execute('INSERT INTO members VALUES("malin.jpg", "Malin", "Malin är grabben som inte tål alkohol. Men han pluggade ju i Halmstad så det kanske inte är så konstigt. Kass på spex och konstant förvirrad.", "2014")')
	c.execute('INSERT INTO members VALUES("referensen.jpg", "&en", "Familjens okrönte musiker. Metalhead ut i fingerspetsarna och har en fantastisk förmåga att sprida glädje kring sig.", "2014")')
	c.execute('INSERT INTO members VALUES("odet.jpg", "Ödet", "Ingen Familjen utan en hipster. Pratar alltid om gains och tror att styrketräning gör en stark. Relativt smart med Familjenmått mätt", "2014")')
	c.execute('INSERT INTO members VALUES("prosten.jpg", "Prosten", "Inga regler utan undantag säger man. Prosten är Familjens undantag. Före detta KK som har en förmåga att alltid säga fel saker vid fel tillfälle. Snäll som få.", "2014")')
	c.execute('INSERT INTO members VALUES("gaia.jpg", "Gaia", "Tjejen som inte blir full och glider omkring och letar efterfester när alla andra gett upp. Den mest normale medlemmen från Halmstad... kanske inte säger så mycket.", "2015")')
	c.execute('INSERT INTO members VALUES("default.jpg", "Windrunner", "Den första kvinnan i Familjen sedan mamma nini. En ödmjuk tjej som till skillnad från de flesta i Familjen faktiskt kan sjunga.", "2015")')

	c.execute("DROP TABLE parties")
	c.execute("CREATE TABLE parties(namne TEXT, year TEXT, link TEXT)")
	c.execute('INSERT INTO parties VALUES("Hjärtslaget", "2008, 2011, 2012, 2013, 2014, 2015", "None")')
	c.execute('INSERT INTO parties VALUES("Absolut Gotland", "2008, 2011, 2012, 2013, 2014, 2015", "None")')
	c.execute('INSERT INTO parties VALUES("Space Station", "2011, 2012", "None")')
	c.execute('INSERT INTO parties VALUES("Rabalder", "2010, 2011, 2012, 2013", "None")')
	c.execute('INSERT INTO parties VALUES("Spiik", "2011, 2012, 2013, 2014, 2015", "None")')
	c.execute('INSERT INTO parties VALUES("Dunder och Brak", "2008, 2011, 2012, 2013, 2014, 2015", "None")')
	c.execute('INSERT INTO parties VALUES("Tjällossningen", "2013", "None")')
	c.execute('INSERT INTO parties VALUES("Bonnaphesten", "2008, 2010", "None")')
	c.execute('INSERT INTO parties VALUES("GRISfesten", "2014, 2015", "None")')
	c.execute('INSERT INTO parties VALUES("Flumride", "2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015", "http://www.brutal-akademien.org/flumride/info")')
	c.execute('INSERT INTO parties VALUES("Fiaslaget", "2011, 2012, 2013, 2014, 2015", "None")')
