# coding=utf-8
import sqlite3

with sqlite3.connect("familjen.db") as connection:
	c = connection.cursor()
	c.execute("DROP TABLE members")
	c.execute("CREATE TABLE members(imageref TEXT, name TEXT, about TEXT, joined TEXT)")
	c.execute('INSERT INTO members VALUES("bob.jpg", "Bob", "En av gudfäderna", "2006")')
	c.execute('INSERT INTO members VALUES("brother.jpg", "brother", "En av gudfäderna", "2006")')
	c.execute('INSERT INTO members VALUES("matte.jpg", "matte", "First", "2006")')
	c.execute('INSERT INTO members VALUES("dalurka.jpg", "dalurka", "First", "2006")')
	c.execute('INSERT INTO members VALUES("linc.jpg", "linc", "Den äldsta människan på planeten", "2006")')
	c.execute('INSERT INTO members VALUES("lunde.jpg", "lunde", "Den hårfagre", "2006")')
	c.execute('INSERT INTO members VALUES("plundra.jpg", "plundra", "*nix, öl och Stroh80", "2006")')
	c.execute('INSERT INTO members VALUES("spaam.jpg", "spaam", "Klicka på hans länkar på IRC", "2006")')
	c.execute('INSERT INTO members VALUES("nini.jpg", "nini", "Alla Familjer behöver en mor. Det här är våran mor!", "2007")')
	c.execute('INSERT INTO members VALUES("elm.jpg", "elm", "Spex, öl och whisky är något som glasblåsarsonen älskar", "2008")')
	c.execute('INSERT INTO members VALUES("ymer.jpg", "Ymer", "Denna långa skåning sjunger mer än gärna. Bjuder alla på beska droppar och älskar kraepthor", "2008")')
	c.execute('INSERT INTO members VALUES("bravo.jpg", "Bravo", "Den yngste i Familjen. Finsmakare av öl som hatar kåren innan han fått i sig minst 4 öl", "2009")')
	c.execute('INSERT INTO members VALUES("strand.jpg", "strand", "Plugga är skoj tyckte strand som påbörjade en ny utbildning efter sin första. Öl tackar han sällan nej till", "2010")')
	c.execute('INSERT INTO members VALUES("string.jpg", "string", "Denna skönsångande göteborgare var den första i Familjen som inte hade sitt ursprung på BTH", "2010")')
	c.execute('INSERT INTO members VALUES("amer.jpg", "Amer", "Ingen vet vilket land han kommer ifrån. En sak är säker. Ger du honom Aurora så börjar han strippa...", "2011")')
	c.execute('INSERT INTO members VALUES("marty.jpg", "Marty", "Misärens ansikte. Blir arg när han inte får köpa Trisslotter på kåren", "2011")')
	c.execute('INSERT INTO members VALUES("poelsa.jpg", "Pölsa", "Nej det är inte den danska korven! Den hårfagre v2.0", "2011")')
	c.execute('INSERT INTO members VALUES("sara.jpg", "Little Waif", "Alltid arg, aldrig nöjd, alltid trevlig", "2012")')
	c.execute('INSERT INTO members VALUES("endl.jpg", "endl;", "Vi har försökt rösta ut honom men han lyckas alltid komma tillbaka", "2012")')
	c.execute('INSERT INTO members VALUES("lautta.jpg", "Lautta", "Även känd som spritLautta. Högljudd skåning som är ganska snäll när hon sover (händer aldrig dock)", "2013")')
	c.execute('INSERT INTO members VALUES("ela.jpg", "ela", "Skönsång och frukost är något ela alltid bidrar med.", "2013")')
	c.execute('INSERT INTO members VALUES("yeti.jpg", "Yeti", "Är man stor måste man vara snäll. Och det är han. Stor alltså...", "2013")')
	c.execute('INSERT INTO members VALUES("wire.jpg", "Wireshark", "Denna killen behöver man inte supar ner, det löser han själv på ett utomordentligt sätt. Kan inte sjunga öht", "2013")')
	c.execute('INSERT INTO members VALUES("mira.jpg", "Mira", "Trots sin ringa storlek hörs och syns hon mest. Energi i överflöd.", "2013")')
	c.execute('INSERT INTO members VALUES("malin.jpg", "Malin", "Hur denna kille lyckats passera 20 är det ingen som vet. Total förvirring", "2014")')
	c.execute('INSERT INTO members VALUES("referensen.jpg", "&en", "Familjens okrönte musiker. Metalhead ut i fingerspetsarna", "2014")')
	c.execute('INSERT INTO members VALUES("odet.jpg", "Ödet", "Ingen Familjen utan en hipster. Pratar alltid om gains", "2014")')
	c.execute('INSERT INTO members VALUES("prosten.jpg", "Prosten", "Omoralisk, creepy och fantastiskt snäll. Stulet gods", "2014")')
	c.execute('INSERT INTO members VALUES("gaia.jpg", "Gaia", "Lite blyg, mycket trevlig, blir aldrig full", "2015")')
	c.execute('INSERT INTO members VALUES("default.jpg", "Windrunner", "Den första kvinnan i Familjen sedan mamma. Kan sjunga!", "2015")')

	c.execute("DROP TABLE parties")
	c.execute("CREATE TABLE parties(namne TEXT, year TEXT, link TEXT)")
	c.execute('INSERT INTO parties VALUES("Hjärtslaget", "2008, 2011, 2012, 2013, 2014, 2015", "None")')
	c.execute('INSERT INTO parties VALUES("Absolut Gotland", "2008, 2011, 2012, 2013, 2014, 2015", "None")')
	c.execute('INSERT INTO parties VALUES("Space Station", "2011, 2012", "None")')
	c.execute('INSERT INTO parties VALUES("Rabalder", "2010, 2011, 2012, 2013", "None")')
	c.execute('INSERT INTO parties VALUES("Spiik", "2011, 2012, 2013, 2014, 2015", "None")')
	c.execute('INSERT INTO parties VALUES("Dunder och Brak", "2008, 2011, 2012, 2013, 2014, 2015", "None")')
	c.execute('INSERT INTO parties VALUES("Tjällossningen", "2013", "None")')
	c.execute('INSERT INTO parties VALUES("Bonnaphesten", "2008, 2010", "None")')
	c.execute('INSERT INTO parties VALUES("GRISfesten", "2014, 2015", "None")')
	c.execute('INSERT INTO parties VALUES("Flumride", "2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015", "http://www.brutal-akademien.org/flumride/info")')
	c.execute('INSERT INTO parties VALUES("Fiaslaget", "2011, 2012, 2013, 2014, 2015", "None")')
